package Grafik;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.category.DefaultCategoryDataset;

public class DiagramBatang extends javax.swing.JPanel {

    private DefaultCategoryDataset dataset;
    
    public DiagramBatang() {
        initComponents();
        this.dataset = new DefaultCategoryDataset();
        this.setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void setData(DefaultCategoryDataset data) {
        this.dataset = data; 
        this.removeAll(); 

        JFreeChart barChart = createChart(dataset); // Menggunakan createChart() untuk menerapkan custom chart
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new Dimension(400, 300));
        this.add(chartPanel, BorderLayout.CENTER);

        this.revalidate(); 
        this.repaint();            
    }

    public JFreeChart createChart(DefaultCategoryDataset dataset){
        JFreeChart barChart = ChartFactory.createBarChart(
                "Grafik Penjualan", 
                "Bulan",            
                "Jumlah Penjualan", 
                dataset); 

        setCustomChart(barChart); // Panggil setCustomChart untuk kustomisasi warna dan font
        return barChart;
    }

    private void setCustomChart(JFreeChart chart){
        TextTitle title = new TextTitle(chart.getTitle().getText(), 
                new Font("SansSerif", Font.BOLD, 14));
        title.setPaint(Color.BLACK);
        chart.setTitle(title);

        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setLabelFont(new Font("SansSerif", Font.BOLD, 12));
        domainAxis.setTickLabelFont(new Font("SansSerif", Font.BOLD, 10));
        domainAxis.setLabelPaint(Color.BLACK);
        domainAxis.setTickLabelPaint(Color.BLACK);

        ValueAxis rangeAxis = plot.getRangeAxis();
        rangeAxis.setLabelFont(new Font("SansSerif", Font.BOLD, 12));
        rangeAxis.setTickLabelFont(new Font("SansSerif", Font.BOLD, 10));
        rangeAxis.setLabelPaint(Color.BLACK);
        rangeAxis.setTickLabelPaint(Color.BLACK);

        plot.setBackgroundPaint(new Color(255,255,255));

        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, new Color(17,97,171)); 
    }
    
}
